### PR TITLE
Generic/FunctionCallArgumentSpacing: improve code coverage

### PR DESCRIPTION
**Pull request by rodrigoprimo**
# Description

This PR improves code coverage for the Generic.Functions.FunctionCallArgumentSpacing sniff.

## Related issues/external references

Part of #146 

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] \[Required for new sniffs\] I have added XML documentation for the sniff.

### CODE REVIEW

**Review by jrfnl — CHANGES_REQUESTED** [review]
Thanks @rodrigoprimo !

The changes as-is are fine.

Having said that, I do think, there are more tests missing, all related to more modern PHP.

There are no tests with attributes, while the sniff does act on them:
```php
#[AttributeName(1,2)]
```

There are no tests with first class callables. While these would not lead to errors being reported or false positives, I still think it would be good to have a test covering that code as the sniff will be triggered for them.
```php
$callable = myCallable(...);
```

----


Other than that **_(not to be addressed in this PR)_**:

The sniff skips over closures, anon classes and (short) arrays which may be passed as a parameter in a function call. It does so to prevent checking the spacing around commas in these (nested) structures, which may have their own rules.

The sniff, however, does not skip over inline `match` control structures, while I think that it should.

The sniff also doesn't skip over arrow functions, while I believe it should do so too. For arrow functions, I can't come up with a code sample which would lead to false positives as any commas would always have to be in nested parentheses or within a short array/match. Having said that, I think skipping them is still the right choice as it makes the sniff slightly more efficient.

Either way, I've prepped a PR to fix these last two (as writing up the issue reminder would take me longer than creating the PR) and will pull that once this PR has been merged (to prevent creating a conflict).

**Comment by rodrigoprimo** [comment]
Thanks for the review, @jrfnl!

> There are no tests with attributes, while the sniff does act on them:
> There are no tests with first class callable.

I added the tests that you suggested.

Regarding the attributes, I added the test you shared that triggers the sniff, and I also added another test that does not trigger the sniff to document the expected behavior. I did not add more tests as it seems to me, for the purposes of this sniff, the attributes behave just like a function call.

**Comment by jrfnl** [comment]
> Regarding the attributes, I added the test you shared that triggers the sniff, and I also added another test that does not trigger the sniff to document the expected behavior.

Well, technically, both code samples trigger the sniff, but only one will trigger an error from the sniff....

**Review by jrfnl — APPROVED** [review]
Thanks @rodrigoprimo !

I will rebase and squash the last commit before merging.

**Comment by jrfnl** [comment]
FYI: I've pulled the follow up mentioned in [one of my previous comments](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/497#pullrequestreview-2063014326) as PR #513

**Pull request merged**
