### PR TITLE
New  `Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence` sniff

### PR DESCRIPTION
**Pull request by TimWolla**
## Description

This is a simple respin of squizlabs/PHP_CodeSniffer#3205 in the new home of PHP CodeSniffer. I've rebased the branch onto the latest master, the resulting diff should be identical, except for package.xml, which no longer exists, and the addition of the XML doc taken from PHPCSStandards/PHPCSExtra#271.

## Suggested changelog entry

Add MixedBooleanOperatorSniff - Forbid mixing different binary boolean operators within a single expression without making precedence clear using parentheses.

## Related issues/external references

Closes squizlabs/PHP_CodeSniffer#3205
Closes PHPCSStandards/PHPCSExtra#271

## Types of changes
- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [x] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist
- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [x] [Required for new sniffs] I have added XML documentation for the sniff.

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
Context for others: this PR has already been extensively reviewed in https://github.com/PHPCSStandards/PHPCSExtra/pull/271 .

---

@TimWolla Thank you for porting this PR over and all your work on it!

I just have two questions (and I'd be happy to fix this up myself as discussed off-GH):
1. In https://github.com/PHPCSStandards/PHPCSExtra/pull/271 we ended up renaming the sniff to `RequireExplicitBooleanOperatorPrecedence`. Is there a pertinent reason why that change was not made for this PR ?
    (this also means there is now a mismatch between the sniff name and the `title` attribute for the docs)
2. In https://github.com/PHPCSStandards/PHPCSExtra/pull/271 the sniff docblock contains some additional information about the choices made for this sniff, while here it contains a code sample. Any particular reason for that ?

Other than that, all good. 👍🏻

**Comment by TimWolla** [comment]
> Is there a pertinent reason why that change was not made for this PR ?

No, this is an oversight. After the review I've copied over just the implementation and tests into squizlabs/PHP_CodeSniffer#3205, because of the differences in code style / namespace between PHPCSExtra and CodeSniffer itself and missed adjusting the "basename" of the Sniff - and this PR is just a respin of that older CodeSniffer PR.

> In https://github.com/PHPCSStandards/PHPCSExtra/pull/271 the sniff docblock contains some additional information about the choices made for this sniff, while here it contains a code sample. Any particular reason for that ?

Yes. Existing Sniffs in CodeSniffer itself contain a code sample within their docblocks. Here's an example: https://github.com/squizlabs/PHP_CodeSniffer/blob/c6c65ca0dc8608ba87631523b97b2f8d5351a854/src/Standards/Generic/Sniffs/CodeAnalysis/JumbledIncrementerSniff.php#L9-L23

--------------------

> and I'd be happy to fix this up myself as discussed off-GH

I'd appreciate if you could perform the last few changes yourself. This would ensure that the result looks exactly like you wish it to be, without a back-and-forth taking up valuable time for both of us - especially since CI would need explicit approval for every additional push I make. But please let me know if I can do something to make that process easier for you (e.g. squashing the existing commits in this PR or so).

**Comment by jrfnl** [comment]
@TimWolla Thanks for your response, I just wanted to verify/confirm, that was all. 👍🏻 

I'll make those last changes myself and will rebase and squash the commits before merging.

**Review by jrfnl — APPROVED** [review]

**Comment by TimWolla** [comment]
Thank you!

**Comment by jrfnl** [comment]
@TimWolla It took a little while, but we got there in the end! Thank you for working with me on this one.

**Comment by TimWolla** [comment]
> It took a little while

3 years and 2 days since opening the first PR on the old CodeSniffer repository 😁

**Comment by jrfnl** [comment]
> > It took a little while
> 
> 3 years and 2 days since opening the first PR on the old CodeSniffer repository 😁

Ouch... well, at least from when we moved it to PHPCSExtra (and active review started) till now is less than five months, so progress. ;-)

**Pull request merged**
