### PR TITLE
Doc: mention the signing key for phars

### LINKED ISSUE #157: Document public key used for phar signing
## Is your feature request related to a problem?

I want to install the phar with phive in CI. This means my script needs to run without user interaction.  For this I hard code the signing key that phive should expect when installing phpcs.

## Describe the solution you'd like

Please document the key that is used to sign the phar in the README or some other obvious place in the documentation. Best would be any "install" section of the docs.

## Additional context (optional)

If the key is not documented any user that installs the phar can just verify that it is signed with *some* key.  The problem is that we have no way of knowing that the key is the intended one.

This is the same argument why browser do not accept self signed tls certificates.

- [ ] I intend to create a pull request to implement this feature.

### PR DESCRIPTION
**Pull request by lucc**
## Description

The signing key used for the phars is mentioned in the README.  This can serve as a "trust anchor" for consumers.

## Related issues/external references

Fixes #157 

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [ ] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.

### CODE REVIEW

**Comment by lucc** [comment]
@jrfnl please verify that this is really your key used for signing the phars :)

**Review by jrfnl — APPROVED** [review]
@lucc Thank you for making these changes 🙏🏻 . I have double and triple checked and yes, that is the correct key 😉

**Comment by theseer** [comment]
> I'm re-reading @theseer's [reply](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/157#issuecomment-1850238790), which now has me wondering if the change to the `phive` command is correct. It uses the public key fingerprint in this PR, but in Arne's example, the command uses the key ID....

No worries. Both are fine. The more common way is to use the key ID but we explicitly also support the full fingerprint. 
If you look at it, you'll see that the ID is actually a part of the fingerprint :)

**Comment by jrfnl** [comment]
@theseer Excellent! Thank you so much for your help and @lucc for preparing this update. Merging now.

**Pull request merged**
