### PR TITLE
Generic/InlineControlStructure: fix two bugs and improve code coverage

### PR DESCRIPTION
**Pull request by rodrigoprimo**
# Description

This PR makes a few changes to the Generic.ControlStructures.InlineControlStructure sniff:

- Fixes a bug when handling `else if` statements (daa1940b80f6de71d3233f17c59e7d47bfb25960) and another one when handling `elseif/if/foreach` without a body (716cbf6f257fddec19c2e162f6458c038ca16220).
- Removes two unreachable conditions (2371f216f7826cf570ebb4ceccf1112639d447ff and 42e2f04d267d2453b2a2d5c599464bd8affcfe52).
- Removes a redundant condition (42e2f04d267d2453b2a2d5c599464bd8affcfe52).
- Removes `T_SWITCH` from the list of tokens that this sniff listens to (3db1049adc9aaf3b5d4f13064e3311e89362f029).
- Improves the code coverage for this sniff (62637cae5238c1b18527ddae0d126a3abf702e11)

While working on this PR, I noticed that the sniff does not handle well a few syntax errors related to the `do-while` control structure. I will open a separate issue describing what I found.

## Suggested changelog entry
Generic.ControlStructures.InlineControlStructure: properly handle `else if` statements where there is a comment between `else` and `if`
Generic.ControlStructures.InlineControlStructure: fix false positives when handling `elseif`, `if`, and `foreach` without a body

## Related issues/external references

Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/146

## Types of changes

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [x] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] \[Required for new sniffs\] I have added XML documentation for the sniff.

### CODE REVIEW

**Review by jrfnl — CHANGES_REQUESTED** [review]
Hi @rodrigoprimo, thank you for yet another PR in this series.

As this PR contains lots of different decision points, it would be better if this would be a series of (chained) PRs, where each of those decisions could be discussed in isolation.

I imagine this PR chain could look something like this:
* PR 1 - commit 1
* PR 2 - commit 2
* PR 3 - commit 6 + 7
* PR 4 - commit 3 + 4 + 5 + 8


Either way, I've reviewed the PR as-is now, going through each commit individually and evaluating each commit on its own merits.

### Commit 1 - error when handling else if

:white_check_mark:


### Commit 2 - stop listening for T_SWITCH

:heavy_check_mark: on the principle of the change, but not on the execution.

While the commit message only mentions PHP, the sniff also checks javascript, so the question needs to be asked whether the conclusion - "`switch` does not support use without curly braces" - is also valid for JS.

I've now verified this via the specs: https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html, but this should have been verified when creating the PR/commit.

For the record, a link to the PHP manual about switch would also have been appropriate here: https://www.php.net/manual/en/control-structures.switch.php

Now, while the token is being removed, the tests still contain quite some code samples with `switch`. These may now no longer be testing anything, while some contain syntax sequences which would be good to have tests for.

Test case file `*.1.inc`:
* line 82-89: related to squizlabs/PHP_CodeSniffer#497 - looks like this test is about `switch` and the alternative syntax, which is no longer relevant in this sniff, but the use of `... ?> ... <?php ...` within a control structure is an interesting case. Can you think of a code sample which would maintain the value of this test, but uses one of the other control structures ?
    Also: should the original test - which was really a tokenizer bug - be moved to a Tokenizer test ?
* line 93 - 96: also related to squizlabs/PHP_CodeSniffer#497 - looks like this test is about `switch` and the alternative syntax, which is no longer relevant in this sniff, but the use of nested alternative syntax control structures could still be a valid test case. Can you think of a code sample which would maintain the value of this test, but uses one of the other control structures ?
    Also: should the original test - which was really a tokenizer bug - be moved to a Tokenizer test ?
* Line 109 - 117: related to squizlabs/PHP_CodeSniffer#543 - looks like this test is about a closure being used within the condition of a `switch`, which is no longer relevant in this sniff, but the use of the closure in the condition is still an interesting case. Can you think of a code sample which would maintain the value of this test, but uses one of the other control structures (without curlies) ?
    Also: should the original test - which was really a tokenizer bug - be moved to a Tokenizer test ?
* Line 146 - 155: related to squizlabs/PHP_CodeSniffer#879 - looks like this test is about mixing if/elseif/else with braces and without braces in one code sample. I imagine, this test is still valid as-is, or maybe the `switch` control structure wrapper should be replaced with another control structure wrapper ?
    Also: should the original test - which was, in part, a tokenizer bug - be moved to a Tokenizer test ?
* Line 204 - 213: related to squizlabs/PHP_CodeSniffer#1590 - looks like this test is about adding braces to an if that's returning a nested function call. I imagine, this test is still valid as-is, or maybe the `switch` control structure wrapper should be replaced with another control structure wrapper ?
    Also: should the original test - which was, in part, a tokenizer bug - be moved to a Tokenizer test ?

Test case file `*.js`:
* line 23 - can a meaningful replacement test be created which would use the keyword of one of the other control structures ?


### Commit 3 - remove unreachable condition

:x:

> The condition is unreachable because `$end` can never be equal to `$phpcsFile->numTokens`. It will always be less than `$phpcsFile->numTokens`. `$end` represents the index of a token in the tokens array. The indexes of the tokens array are zero-based, and the `$phpcsFile->numTokens` property is one-based. So even if `$end` is pointing to the index of the last token, it will be less than `$phpcsFile->numTokens`.
> 
> `$end` is first set as `$end = ($closer + 1)`. In theory, if `$closer` is the index of the last token, `$end` could be equal to `$phpcsFile->numTokens`. But that is a situation that will never occur as it will represent a syntax error, and the sniff would have bailed already.

Would have been nice to have an indication of *where* the sniff would bail early as the `for` loop setting `$end` doesn't contain a `return` statement, so, based on that code alone, it is perfectly possible for `$end === $phpcs->numTokens` to be `true`.

With this in mind, I've now investigated this myself and find that the above statement is just not true. The `$end === $phpcs->numTokens` is definitely reachable and removing it introduces a bug in the sniff.

This commit should be dropped and a new test case file should be added with the following code (note: NO new line or semicolon at the end of the file!):

```php
<?php
// Live coding. Should still trigger the error.
// This test should explicitly NOT contain a new line at the end of the file.
if ($bar)
   doSomething()
```

### Commit 4 - test case file rename

:ballot_box_with_check:

### Commit 5 - remove redundant condition

:heavy_check_mark:

While I have verified the claim made in the commit message and found it correct, I haven't dug in deeper to see if anything else could break.

The reason for this is two-fold:
1. This is JS specific code and using PHPCS with JS is already discouraged and support will be removed in the near future.
2. The code snippet being removed looks to be unstable anyway as the unlimited `find*()` calls can walk way too far.


### Commit 6 - bug when handling * without body

:question:

:grin: Actually, I did consider that case when creating squizlabs/PHP_CodeSniffer#2827 - see: https://github.com/squizlabs/PHP_CodeSniffer/pull/2827#issuecomment-580482646. At the time, we decided not to handle it as none of those code samples make for useful/effective code. That kind of code would always effectively be redundant code.

If that type of code would now be handled by the sniff, let's do it correctly. Even an `else` without a body is valid: https://3v4l.org/W2Bao, so excluding `else` from this check is incorrect.

Also note that as commit 5 removes the JS specific block, this change will now also affect JS code, so it will need tests in the JS file and it should be verified if the change is even valid for JS.

Other notes:

As you intend for that code sample to now run for nearly all tokens this sniff listens for, the new condition can be simplified to:
```diff
-if (in_array($tokens[$stackPtr]['code'], [T_ELSEIF, T_IF, T_FOR, T_FOREACH, T_WHILE], true) === true) {
+if ($tokens[$stackPtr]['code'] !== T_DO) {
```

I also think the condition on [line 181](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/72b50b9aa22b65fd41be21a5de272d53a327d125/src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php#L181) can now no longer be `true`, so is redundant ?



### Commit 7 - remove redundant condition

:question:

If accepted, this commit should be included in commit 6, as that is the commit which makes the code redundant. It wasn't redundant before, it was only missing tests to  trigger the code.

_Note for future reviews: this commit is easier to evaluate when ignoring whitespace._

Looking at this more closely, I think this needs further investigation before this commit could be considered.

While looking at this in combination with the review for commit 3, I started wondering about [line 280](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/72b50b9aa22b65fd41be21a5de272d53a327d125/src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php#L280). I have a niggly feeling that that `findNext()` could return `false` and needs a test + safeguard.

As things are, without digging deeper into the potentially problematic result of line 280, the code snippet you are proposing to remove, cannot be removed, as if line 280 would return `false`, the `if ($next !== $end)` condition could be a `false !== $end`, which means that the code snippet being removed would be hit and the fixer would end up creating a parse error in the file under scan.


### Commit 8 - improve code coverage

What with some of the above commit being pulled into question, this commit cannot be verified properly until the other questions have been resolved and the code has been updated to reflect this.

**Comment by rodrigoprimo** [comment]
Closing this PR. As discussed via chat, I will open smaller PRs following @jrfnl suggestion:

> PR 1 - commit 1
> PR 2 - commit 2
> PR 3 - commit 6 + 7
> PR 4 - commit 3 + 4 + 5 + 8

**Comment by jrfnl** [comment]
@rodrigoprimo The first follow-up PR, cherrypicked out of this PR was pulled and merged a while ago. What is the status of the rest ?

**Comment by rodrigoprimo** [comment]
@jrfnl, I started working on the issues related to commit 2, but I paused because I wasn't sure about the changes that I was making to the tokenizer tests. I plan to discuss this with you in our pairing session tomorrow. I can create an issue (or a few issues) for the items that are still pending after our conversation tomorrow.

**Comment by jrfnl** [comment]
> I can create an issue (or a few issues) for the items that are still pending after our conversation tomorrow.

@rodrigoprimo That sounds like a good idea as it will allow us to track what still needs doing more easily (at least more easily than to remember to look at a closed issue)

**Pull request closed without merging**
