### PR TITLE
Generic/UnnecessaryFinalModifier: improve code coverage

### PR DESCRIPTION
**Pull request by rodrigoprimo**
## Description

This PR improves the code coverage of the Generic.CodeAnalysis.UnnecessaryFinalModifier sniff. There was only one line that was not already exercised by the tests that bails early if it finds a class without a body.

I considered adding more tests with different class definitions, but I was not able to think of examples that felt relevant enough and also different enough from the tests that are already in place.

## Related issues/external references

Part of #146 

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added XML documentation for the sniff.

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
Thanks for this PR @rodrigoprimo !

> I considered adding more tests with different class definitions, but I was not able to think of examples that felt relevant enough and also different enough from the tests that are already in place.

What about adding some tests with [`final` class constants](https://wiki.php.net/rfc/final_class_const) as allowed since PHP 8.1 ?

**Comment by rodrigoprimo** [comment]
Thanks for the review, @jrfnl!

> What about adding some tests with [final class constants](https://wiki.php.net/rfc/final_class_const) as allowed since PHP 8.1 ?

Good point, I just pushed a new commit adding tests with final class constants.

**Review by jrfnl — APPROVED** [review]
Thanks for adding those extra tests @rodrigoprimo !

**Comment by jrfnl** [comment]
FYI: I've rebased the PR without changes to get the code coverage to report. Will merge once the build passes.
image

**Pull request merged**
