### PR TITLE
Fixed pattern replacements in Filter.php

### PR DESCRIPTION
**Pull request by arturm11**
Fixed bad pattern replacements. Eliminates warnings when used as PHP Sniffer extension in VSCode.

# Description

If full Windows path is used as ignore filter in shouldIgnorePath() function, then conversion to PREG pattern was buggy.
Windows backslash separator should be converted into double backslash (escaped backslash) AND Linux slash separator should be converted into double backslash.

## Suggested changelog entry

Add backslash into double backslash replacement for Windows.

## Related issues/external references

PHP Sniffer extension for VSCode generates warnings on Windows without this fix.

## Types of changes

- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [x] I have read the [Contribution Guidelines](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] \[Required for new sniffs\] I have added XML documentation for the sniff.

### CODE REVIEW

**Comment by jrfnl** [comment]
@arturm11 Thank you for this PR.

I've been able to reproduce the issue with PHPCS itself via the command line using something along the lines of:
```bash
phpcs --ignore=D:\path\to\PHP_CodeSniffer\src\Tokenizers\CSS.php
```

which results in a:
```
Warning: preg_match(): Compilation failed: unknown property after \P or \p at offset * in D:\path\to\PHP_CodeSniffer\src\Filters\Filter.php on line 278
```

And the change made in this PR fixes this. :+1:

Before I can accept the PR, could you please have a look at the third checklist item in the "PR checklist" ?

I'd also like to see this change safeguarded via tests. There are some tests for the Filters in the `tests/Core/Filters` directory already. These could probably be expanded.

**Comment by arturm11** [comment]
@jrfnl Now I am not sure. Please analyze [Ignoring Files and Folders](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders) section in the wiki. It is stated, that filter can be treated as regular expression. Backslash character is special character for RE. Therefore Windows paths shouldn't be accepted and backslash should be converted to slash in Windows path on input.

**Comment by arturm11** [comment]
There is related bug in vscode-php-sniffer, so I close this request.
https://github.com/wongjn/vscode-php-sniffer/pull/73

**Comment by jrfnl** [comment]
@arturm11 Thanks for getting back to me. Hope that bug gets fixed soon.

**Pull request closed without merging**
